version: '3.7'

services:
  db:
    image: 'mongo:latest'
    restart: always
    volumes:
      - 'mongo-vol:/data/db'
    networks:
      - minenetworken
  cms:
    image: thacockpit:latest
    restart: unless-stopped
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: 79a04ac4-e943-4373-b5fd-81b23e2de378
      COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
      COCKPIT_DATABASE_NAME: cockpit_master
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - minenetworken
  
networks:
  minenetworken:
      driver: bridge
volumes:
  mongo-vol: null